export const id = "id"
export const handCount = "handCount"
export const weaponType = "weaponType"
export const lvl = "lvl"
export const titleRu = "titleRu"
export const titleEn = "titleEn"
export const source = "source"
export const price = "price"
export const damage = "damage"
export const damageType = "damageType"
export const critical = "critical"
export const weight = "weight"
export const special = "special"

export default titleRu;